// <auto-generated />
using System;
using Encore.Api.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Encore.Api.Persistence.Migrations
{
    [DbContext(typeof(EncoreDbContext))]
    partial class EncoreDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Encore.Api.Persistence.AuditEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<int?>("Created")
                        .HasColumnType("integer")
                        .HasColumnName("created");

                    b.Property<string>("TenantId")
                        .HasColumnType("text")
                        .HasColumnName("tenant");

                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Created")
                        .HasDatabaseName("audit_tenant");

                    b.ToTable("audit", (string)null);
                });

            modelBuilder.Entity("Encore.Api.Persistence.Guest", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<int>("Created")
                        .HasColumnType("integer")
                        .HasColumnName("created");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<int>("Terms")
                        .HasColumnType("integer")
                        .HasColumnName("terms");

                    b.HasKey("Id");

                    b.HasIndex("Phone")
                        .IsUnique()
                        .HasDatabaseName("guests_phone_key");

                    b.ToTable("guests", (string)null);
                });

            modelBuilder.Entity("Encore.Api.Persistence.GuestSession", b =>
                {
                    b.Property<string>("Token")
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.Property<int>("Expires")
                        .HasColumnType("integer")
                        .HasColumnName("expires");

                    b.Property<string>("GuestId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("guest");

                    b.HasKey("Token");

                    b.HasIndex("Expires")
                        .HasDatabaseName("guest_sessions_expires");

                    b.HasIndex("GuestId");

                    b.ToTable("guest_sessions", (string)null);
                });

            modelBuilder.Entity("Encore.Api.Persistence.Invite", b =>
                {
                    b.Property<string>("Token")
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<int>("Expires")
                        .HasColumnType("integer")
                        .HasColumnName("expires");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant");

                    b.HasKey("Token");

                    b.HasIndex("Expires")
                        .HasDatabaseName("invites_expires");

                    b.HasIndex("TenantId");

                    b.ToTable("invites", (string)null);
                });

            modelBuilder.Entity("Encore.Api.Persistence.Notification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<long>("Id"));

                    b.Property<string>("Audience")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("audience");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<int>("Created")
                        .HasColumnType("integer")
                        .HasColumnName("created");

                    b.Property<string>("GuestId")
                        .HasColumnType("text")
                        .HasColumnName("guest");

                    b.Property<string>("Kind")
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<int>("Read")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("read");

                    b.Property<string>("Ref")
                        .HasColumnType("text")
                        .HasColumnName("ref");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("GuestId", "Created")
                        .HasDatabaseName("notifications_guest");

                    b.HasIndex("TenantId", "Audience", "Created")
                        .HasDatabaseName("notifications_tenant");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("Encore.Api.Persistence.Otp", b =>
                {
                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<int>("Attempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("attempts");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<int>("Expires")
                        .HasColumnType("integer")
                        .HasColumnName("expires");

                    b.Property<int>("Sent")
                        .HasColumnType("integer")
                        .HasColumnName("sent");

                    b.HasKey("Phone");

                    b.ToTable("otps", (string)null);
                });

            modelBuilder.Entity("Encore.Api.Persistence.OtpLogEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<long>("Id"));

                    b.Property<int>("Created")
                        .HasColumnType("integer")
                        .HasColumnName("created");

                    b.Property<string>("Ip")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ip");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.HasKey("Id");

                    b.HasIndex("Phone", "Created")
                        .HasDatabaseName("otp_log_phone");

                    b.ToTable("otp_log", (string)null);
                });

            modelBuilder.Entity("Encore.Api.Persistence.PlatformAdmin", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<int>("Created")
                        .HasColumnType("integer")
                        .HasColumnName("created");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("platform_admins_email_key");

                    b.ToTable("platform_admins", (string)null);
                });

            modelBuilder.Entity("Encore.Api.Persistence.PlatformAuditEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<string>("AdminId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("admin");

                    b.Property<int>("Created")
                        .HasColumnType("integer")
                        .HasColumnName("created");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("")
                        .HasColumnName("detail");

                    b.Property<string>("Target")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("")
                        .HasColumnName("target");

                    b.HasKey("Id");

                    b.ToTable("platform_audit", (string)null);
                });

            modelBuilder.Entity("Encore.Api.Persistence.PlatformSession", b =>
                {
                    b.Property<string>("Token")
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.Property<string>("AdminId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("admin");

                    b.Property<int>("Expires")
                        .HasColumnType("integer")
                        .HasColumnName("expires");

                    b.HasKey("Token");

                    b.HasIndex("AdminId");

                    b.HasIndex("Expires")
                        .HasDatabaseName("platform_sessions_expires");

                    b.ToTable("platform_sessions", (string)null);
                });

            modelBuilder.Entity("Encore.Api.Persistence.Rating", b =>
                {
                    b.Property<string>("TenantId")
                        .HasColumnType("text")
                        .HasColumnName("tenant");

                    b.Property<string>("GuestId")
                        .HasColumnType("text")
                        .HasColumnName("guest");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("")
                        .HasColumnName("comment");

                    b.Property<int>("Created")
                        .HasColumnType("integer")
                        .HasColumnName("created");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Stars")
                        .HasColumnType("integer")
                        .HasColumnName("stars");

                    b.Property<int>("Updated")
                        .HasColumnType("integer")
                        .HasColumnName("updated");

                    b.HasKey("TenantId", "GuestId");

                    b.HasIndex("GuestId");

                    b.ToTable("ratings", (string)null);
                });

            modelBuilder.Entity("Encore.Api.Persistence.StaffSession", b =>
                {
                    b.Property<string>("Token")
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.Property<int>("Expires")
                        .HasColumnType("integer")
                        .HasColumnName("expires");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user");

                    b.HasKey("Token");

                    b.HasIndex("Expires")
                        .HasDatabaseName("sessions_expires");

                    b.HasIndex("UserId");

                    b.ToTable("sessions", (string)null);
                });

            modelBuilder.Entity("Encore.Api.Persistence.Tenant", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<int>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("created");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("active")
                        .HasColumnName("status");

                    b.Property<string>("StatusNote")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("")
                        .HasColumnName("status_note");

                    b.Property<int?>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("Encore.Api.Persistence.Upload", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Created")
                        .HasColumnType("integer")
                        .HasColumnName("created");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("data");

                    b.Property<string>("Mime")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mime");

                    b.HasKey("Name");

                    b.HasIndex("Created")
                        .HasDatabaseName("uploads_created");

                    b.ToTable("uploads", (string)null);
                });

            modelBuilder.Entity("Encore.Api.Persistence.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("")
                        .HasColumnName("avatar");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("Recovery")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("recovery");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("users_email_key");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("users_tenant");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Encore.Api.Persistence.GuestSession", b =>
                {
                    b.HasOne("Encore.Api.Persistence.Guest", null)
                        .WithMany()
                        .HasForeignKey("GuestId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Encore.Api.Persistence.Invite", b =>
                {
                    b.HasOne("Encore.Api.Persistence.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Encore.Api.Persistence.PlatformSession", b =>
                {
                    b.HasOne("Encore.Api.Persistence.PlatformAdmin", null)
                        .WithMany()
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Encore.Api.Persistence.Rating", b =>
                {
                    b.HasOne("Encore.Api.Persistence.Guest", null)
                        .WithMany()
                        .HasForeignKey("GuestId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Encore.Api.Persistence.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Encore.Api.Persistence.StaffSession", b =>
                {
                    b.HasOne("Encore.Api.Persistence.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Encore.Api.Persistence.User", b =>
                {
                    b.HasOne("Encore.Api.Persistence.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
