// Branded PDF reports (Encore platform + organization). jsPDF is loaded only when exporting.

const CRIMSON = [230, 30, 50];
const INK = [13, 13, 18];
const MUTED = [102, 109, 128];
const LINE = [233, 234, 237];

const MARK_SVG = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><defs><mask id="m"><rect width="100" height="100" fill="#fff"/><path d="M31 44c2-11 9.5-18 19.5-18S68 33 69.5 44z" fill="#000"/><path d="M31 56h69v10H62c-3 6-8 9-13 9-8.5 0-15.5-6-18-19z" fill="#000"/><circle cx="4" cy="52" r="6" fill="#000"/></mask></defs><circle cx="50" cy="50" r="46" fill="#E61E32" mask="url(#m)"/></svg>`;

function loadImage(src) {
  return new Promise((resolve, reject) => {
    const img = new Image();
    img.onload = () => resolve(img);
    img.onerror = reject;
    img.src = src;
  });
}

/** Rasterize an image (SVG data or uploaded photo URL) to a square PNG data URL for jsPDF. */
async function toPng(src, size = 256, round = false) {
  try {
    const img = await loadImage(src);
    const canvas = document.createElement('canvas');
    canvas.width = canvas.height = size;
    const ctx = canvas.getContext('2d');
    if (round) {
      ctx.beginPath();
      ctx.roundRect(0, 0, size, size, size * 0.22);
      ctx.clip();
    }
    const scale = Math.max(size / img.width, size / img.height);
    const w = img.width * scale, h = img.height * scale;
    ctx.drawImage(img, (size - w) / 2, (size - h) / 2, w, h);
    return canvas.toDataURL('image/png');
  } catch {
    return null;
  }
}

/**
 * Build and download a report.
 * sections: [{ title, kpis?: [[label, value]], table?: { head: [...], body: [[...]], align?: {colIndex: 'right'} }, note? }]
 */
export async function exportPdf({ filename, title, subtitle, organization, logo, sections, kind = 'Organizer report' }) {
  const [{ jsPDF }, { default: autoTable }] = await Promise.all([import('jspdf'), import('jspdf-autotable')]);
  const doc = new jsPDF({ unit: 'pt', format: 'a4' });
  const W = doc.internal.pageSize.getWidth();
  const H = doc.internal.pageSize.getHeight();
  const M = 40;
  const mark = await toPng('data:image/svg+xml;charset=utf-8,' + encodeURIComponent(MARK_SVG), 128);
  const orgLogo = logo ? await toPng(logo, 160, true) : null;
  const generated = new Date().toLocaleString(undefined, { dateStyle: 'medium', timeStyle: 'short' });

  const header = () => {
    doc.setFillColor(...INK);
    doc.rect(0, 0, W, 96, 'F');
    if (mark) doc.addImage(mark, 'PNG', M, 26, 22, 22);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(16);
    doc.setTextColor(255, 255, 255);
    doc.text('encore', M + 28, 42);
    doc.setFontSize(8);
    doc.setTextColor(180, 180, 188);
    doc.text('LIVE MOMENTS, BEAUTIFULLY RUN', M, 64);
    const right = W - M;
    let textRight = right;
    if (orgLogo) {
      doc.addImage(orgLogo, 'PNG', right - 40, 26, 40, 40);
      textRight = right - 50;
    }
    doc.setFontSize(13);
    doc.setTextColor(255, 255, 255);
    doc.text(organization, textRight, 42, { align: 'right' });
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8.5);
    doc.setTextColor(180, 180, 188);
    doc.text(kind, textRight, 58, { align: 'right' });
    doc.setFillColor(...CRIMSON);
    doc.rect(0, 96, W, 3, 'F');
  };
  const footer = () => {
    const pages = doc.getNumberOfPages();
    for (let i = 1; i <= pages; i++) {
      doc.setPage(i);
      doc.setDrawColor(...LINE);
      doc.line(M, H - 42, W - M, H - 42);
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(8);
      doc.setTextColor(...MUTED);
      doc.text(`${organization} · Generated by Encore · ${generated}`, M, H - 26);
      doc.text(`Page ${i} of ${pages}`, W - M, H - 26, { align: 'right' });
    }
  };

  header();
  let y = 130;
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(22);
  doc.setTextColor(...INK);
  doc.text(title, M, y);
  if (subtitle) {
    y += 18;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(...MUTED);
    doc.text(subtitle, M, y);
  }
  y += 26;

  const ensure = needed => {
    if (y + needed > H - 60) {
      doc.addPage();
      header();
      y = 130;
    }
  };

  for (const section of sections) {
    ensure(60);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    doc.setTextColor(...CRIMSON);
    doc.text(section.title.toUpperCase(), M, y);
    y += 12;

    if (section.kpis) {
      const cols = 3;
      const gap = 10;
      const cw = (W - M * 2 - gap * (cols - 1)) / cols;
      const hints = section.kpis.some(k => k[2]);
      const th = hints ? 62 : 50;
      let rowTop = y;
      section.kpis.forEach(([label, value, hint], i) => {
        const col = i % cols;
        const x = M + col * (cw + gap);
        if (col === 0 && i > 0) rowTop += th + 8;
        if (col === 0 && rowTop + th > H - 60) {
          doc.addPage();
          header();
          rowTop = 130;
        }
        const top = rowTop;
        doc.setFillColor(247, 247, 249);
        doc.setDrawColor(...LINE);
        doc.roundedRect(x, top, cw, th, 6, 6, 'FD');
        if (hint) {
          doc.setFont('helvetica', 'normal');
          doc.setFontSize(7.5);
          doc.setTextColor(...MUTED);
          doc.text(doc.splitTextToSize(String(hint), cw - 20)[0], x + 10, top + 53);
        }
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(8.5);
        doc.setTextColor(...MUTED);
        doc.text(label, x + 10, top + 17);
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(14);
        doc.setTextColor(...INK);
        doc.text(String(value), x + 10, top + 38);
      });
      y = rowTop + th + 22;
    }

    if (section.table) {
      const { head, body, align = {} } = section.table;
      autoTable(doc, {
        startY: y + 2,
        head: [head],
        body: body.length ? body : [[{ content: 'No data for this period.', colSpan: head.length, styles: { textColor: MUTED, halign: 'center' } }]],
        margin: { left: M, right: M, top: 120, bottom: 60 },
        styles: { font: 'helvetica', fontSize: 9, cellPadding: 6, textColor: INK, lineColor: LINE, lineWidth: 0.5 },
        headStyles: { fillColor: INK, textColor: 255, fontStyle: 'bold' },
        alternateRowStyles: { fillColor: [250, 250, 251] },
        columnStyles: Object.fromEntries(Object.entries(align).map(([k, v]) => [k, { halign: v }])),
        didParseCell: data => { if (data.section === 'head' && align[data.column.index]) data.cell.styles.halign = align[data.column.index]; },
        didDrawPage: data => { if (data.pageNumber > 1) header(); },  // table continued on a new page
      });
      y = doc.lastAutoTable.finalY + 22;
    }

    if (section.note) {
      ensure(30);
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(8.5);
      doc.setTextColor(...MUTED);
      const lines = doc.splitTextToSize(section.note, W - M * 2);
      doc.text(lines, M, y);
      y += lines.length * 11 + 14;
    }
  }

  footer();
  doc.save(filename);
}
